- name: Jenkins requirements installs
  become: true
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: "default-jdk", state: "present" }
    - { name: "fontconfig", state: "present"}

- name: Install Jenkins Plugin Manager && Jenkins key
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar",
        dest: "/tmp/jenkins-plugin-manager-2.13.2.jar", mode: '0644' }
    - { url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key",
        dest: "/usr/share/keyrings/jenkins-keyring.asc", mode: '0644' }

- name: Add Jenkins repository to sources list
  become: true
  lineinfile:
    path: "/etc/apt/sources.list.d/jenkins.list"
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    create: yes

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install jenkins
  become: true
  apt:
    name: "jenkins"
    state: "present"

- name: Stop jenkins
  become: true
  systemd:
    name: "jenkins"
    state: "stopped"

- name: Create groovy folder
  become: true
  ansible.builtin.file:
    path: /usr/share/jenkins/init.groovy.d
    state: directory


- name: Copy jenkins files without templates
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "{{ playbook_dir }}/../images/", dest: "/images/", owner: "jenkins", group: jenkins, mode: '0644'}
    - { src: "../files/linkproject.sh", dest: "/usr/bin", owner: "jenkins", group: jenkins, mode: '0774'}
    - { src: "../files/job_dsl.groovy", dest: /usr/share/jenkins/init.groovy.d/job_dsl.groovy", owner: "jenkins",
        group: "jenkins", mode: "0644"}

- name: Copy jenkins files using templates
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "../files/plugins.txt", dest: "/tmp/plugins.txt", owner: "jenkins", group: jenkins, mode: '0644'}
    - { src: "./files/jenkins.yml", dest: "/usr/bin", owner: "jenkins", group: jenkins, mode: '0644' }


- name: Replace Java OPTS 
  become: true
  ansible.builtin.replace:
    path: "/lib/systemd/system/jenkins.service"
    regexp: '^Environment="JAVA_OPTS=.*'
    replace: 'Environment="JAVA_OPTS={{ JAVA_OPTS }}"'

- name: Start plugin cli
  become: true
  command: "java -jar /tmp/jenkins-plugin-manager-2.13.2.jar --plugin-file /tmp/plugins.txt \
  --plugin-download-directory /var/lib/jenkins/plugins"

- name: Add jenkins to docker group
  become: true
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Start jenkins
  become: true
  systemd:
    name: "jenkins"
    state: "started"
    daemon-reload: yes
