- name: Install Java 17
  become: true
  apt:
    name: "default-jdk"
    state: "present"

- name: Install fontconfig
  become: true
  apt:
    name: "fontconfig"
    state: "present"

- name: Install Jenkins plugin manager
  become: true
  get_url:
    url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar"
    dest: "/tmp/jenkins-plugin-manager-2.13.2.jar"

- name: Download jenkins key
  become: true
  get_url:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    dest: "/usr/share/keyrings/jenkins-keyring.asc"
    mode: '0644'

- name: Add Jenkins repository to sources list
  become: true
  lineinfile:
    path: "/etc/apt/sources.list.d/jenkins.list"
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    create: yes

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install jenkins
  become: true
  apt:
    name: "jenkins"
    state: "present"

- name: Stop jenkins
  become: true
  systemd:
    name: "jenkins"
    state: "stopped"

- name: Copy docker images
  become: true
  copy:
   src: "{{ playbook_dir }}/../images/"
   dest: "/images/"

- name: Copy linkproject shell
  become: true
  copy:
    src: "../files/linkproject.sh"
    dest: "/usr/bin/"
    owner: jenkins
    group: jenkins
    mode: '0774'

- name: Copy plugin file
  become: true
  template:
    src : "../files/plugins.txt"
    dest: "/tmp/plugins.txt"

- name: Copy Jenkins yml
  become: true
  template:
    src: "../files/jenkins.yml"
    dest: "/var/lib/jenkins/jenkins.yml"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Create groovy folder
  become: true
  ansible.builtin.file:
    path: /usr/share/jenkins/init.groovy.d
    state: directory

- name: Copy jobdsl groovy
  become: true
  copy: 
    src: "../files/job_dsl.groovy"
    dest: "/usr/share/jenkins/init.groovy.d/job_dsl.groovy"

- name: Replace Java OPTS 
  become: true
  ansible.builtin.replace:
    path: "/lib/systemd/system/jenkins.service"
    regexp: '^Environment="JAVA_OPTS=.*'
    replace: 'Environment="JAVA_OPTS={{ JAVA_OPTS }}"'

- name: Start plugin cli
  become: true
  command: "java -jar /tmp/jenkins-plugin-manager-2.13.2.jar --plugin-file /tmp/plugins.txt \
  --plugin-download-directory /var/lib/jenkins/plugins"

- name: Add jenkins to docker group
  become: true
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Start jenkins
  become: true
  systemd:
    name: "jenkins"
    state: "started"
    daemon-reload: yes
