FROM maven:3.9.9-amazoncorretto-21 AS builder

ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD RUN mvn dependency:resolve
ONBUILD RUN mvn package

FROM amazoncorretto:21

ONBUILD COPY --from=builder /app/target /app
ONBUILD WORKDIR /app

ONBUILD CMD java -jar app.jar
