FROM maven:3.9.9-eclipse-temurin-21 AS builder

COPY . /app
WORKDIR /app/app/

RUN mvn dependency:resolve
RUN mvn package

FROM eclipse-temurin:21-jdk-alpine

COPY --from=builder /app/app/target /app
WORKDIR /app

RUN rm -rf archive-tmp classes generated-sources generated-test-sources maven-archiver \
maven-status surefire-reports test-classes

CMD java -jar app.jar
