FROM maven:3.9.9-amazoncorretto-21 AS builder

COPY . /app
WORKDIR /app

RUN mvn dependency:resolve
RUN mvn package

FROM amazoncorretto:21

COPY --from=builder /app/target /app
WORKDIR /app

CMD java -jar app.jar
