replicas: 1
image:
  repository: <your-registry>.azurecr.io/whanos
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

service:
  type: LoadBalancer
  port: 80
