services:
  whanos_jenkins:
    container_name: whanos_jenkins
    build:
      context: ./
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8080:8080"
      - "50000:50000"

