- name: base
  hosts: all
  roles:
    - base
  tags:
    - base

- name: jenkins
  hosts: azure
  roles:
    - jenkins
  tags:
    - jenkins

- name: nginx
  hosts: azure
  roles:
    - nginx
  tags:
    - nginx

- name: kube
  hosts: azure
  roles:
    - kube
  tags:
    - kube
