- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Remove Nginx default virtual host
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx reverse proxy conf
  become: true
  template:
    src: "../files/default.conf"
    dest: "/etc/nginx/conf.d/default.conf"

- name: Start nginx service
  become: true
  service:
    name: nginx
    state: restarted
    daemon-reload: yes