FROM python:3.12-alpine

COPY . /app
WORKDIR /app

RUN if [ -f requirements.txt ]; then \
        pip install --no-cache-dir -r requirements.txt; \
    fi

RUN rm -rf /app/* && rm -rf /tmp/* /var/tmp/*

CMD ["python", "-m", "app"]
