FROM python:3.12-alpine

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt
RUN rm -rf Dockerfile.standalone Dockerfile.base /tmp/* /var/tmp/* requirements.txt

CMD ["python", "-m", "app"]
