FROM python:3.12-alpine

ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD RUN pip install --no-cache-dir -r requirements.txt
ONBUILD RUN rm -rf Dockerfile.standalone Dockerfile.base /tmp/* /var/tmp/* requirements.txt

ONBUILD CMD ["python", "-m", "app"]
