FROM python:3.12-alpine

ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD RUN pip install --no-cache-dir -r requirements.txt

ONBUILD RUN rm -rf /app/* && rm -rf /tmp/* /var/tmp/*

ONBUILD CMD ["python", "-m", "app"]
