FROM python:3.12-alpine

ONBUILD RUN apk add --no-cache bash
ONBUILD SHELL ["/bin/bash", "-c"]

ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD RUN pip install --no-cache-dir -r requirements.txt
ONBUILD RUN rm -rf Dockerfile.standalone Dockerfile.base /tmp/* /var/tmp/* requirements.txt

ONBUILD CMD ["python", "-m", "app"]
