- name: Update VM
  become: true
  apt:
    update_cache: true
  
- name: Upgrade VM
  become: true
  apt:
    upgrade: "full"

- name: Install basics package for any VM
  become: true
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: git, state : present }
    - { name: zip, state : present }
    - { name: tar, state : present }
    - { name: curl, state : present }
    - { name: wget, state : present }
    - { name: python3, state : present }
    - { name: python3-pip, state : present }
    - { name: docker*, state : present }
