FROM node:20.9.0-alpine

ONBUILD COPY . /app
ONBUILD WORKDIR /app

ONBUILD EXPOSE 3000
ONBUILD RUN npm install

ONBUILD RUN rm -rf Dockerfile.standalone Dockerfile.base package-lock.json

ONBUILD CMD node .
