FROM node:20.9.0-alpine

RUN apk add --no-cache bash
SHELL ["/bin/bash", "-c"]

COPY . /app
WORKDIR /app

EXPOSE 3000
RUN npm install
RUN rm -rf Dockerfile.standalone Dockerfile.base package-lock.json

CMD node .
