name: mirror_push
on:
  push:
    branches:
      - main
env:
  MIRROR_URL:
    git@github.com:EpitechPromo2027/B-DOP-500-REN-5-1-whanos-arthur.doriel.git

jobs:
  push_to_mirror:
    if : github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}